config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }, path_names: {sign_in: "login", sign_out: "logout"}
  resources 'users'
  resources 'student_group'
  resources 'students'
  resources 'student_notes'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get 'tags/:id/:tag', to: 'students#show', as: :tag
  get '/:student_group', to: 'static_pages#home', as: :student_group_homepage
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include StaticPagesHelper
  
  def home
    @note = StudentNote.new
    @title = "Anecdotal Notes"
    @selected_class = StudentGroup.find(cookies[:selected_student_group_id]) if  StudentGroup.where(id:cookies[:selected_student_group_id]).count > 0
    @student_groups = current_user.student_groups if user_signed_in?
    if params[:student_group]
      set_student_group_cookie(params[:student_group])
      redirect_to root_url
    end
  end

  def help
    @title = "FAQ/Help"
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def set_student_group_cookie(id)
    if StudentGroup.where(id:id).count > 0
      cookies[:selected_student_group_id] = id
    else
      cookies.delete(:selected_student_group_id)
    end
  end
  

end

app/views/static_pages/_welcome_page.html.erb
<div class="col-md-10 col-md-offset-1 welcomepage">
  <p>
    Anecdotal notes can be used to keep records of individual student skills and behaviors over time.  A system of keeping these notes lets teachers document and review ongoing patterns or student development over time, and can be useful to share with the student, parents or administrators.
  </p>
  <p>
    Typically, these systems involve large binders with dividers for each student, and a system of filing with sticky notes or labels.  Such systems, while incredibly useful in the classroom can become unweildy over time.
  </p>
  <p>
    <strong>This system,</strong> is a digital implementation of  those large notebooks allowing users to quickly and easily keep individual notebooks for every student in every class.  Notes can be viewed by student and can easily be sorted using tags
  </p>
  <a href=<%= new_user_registration_url %>><button type="button" name="button" class="btn btn-primary">Try it out now!</button></a>
  </div>

app/views/static_pages/help.html.erb
<h3>Adding Classes and Students</h3>
<p>
  Create new classes and then add students to them from your <%= link_to "profile page", current_user %>.
</p>
<h3>Creating Notes</h3>
<p>
  To add student notes, select the student from the dropdown menu on the new note page, type a note, add optional tags and then click "create note"
</p>
<h3>Viewing Notes</h3>
<p>
  To view notes, go to the class and then select a student to view.  If notes have been created with tags, you can filter the notes by tag on the student's view page.  You can edit notes and add or remove tags from this page as well by clicking the edit symbol on the top right of each note.
</p>
<h3>General Tips:</h3>
<ul>
  <li>Record your notes as soon as possible following observation.  If you teach using a tablet or if your admins allow you to use your phone for classroom use you can add notes quickly while walking around the room.</li>
  <li>You can use as many tags as you like on each note, but using too many can reduce their usefulness</li>
  <li>Elementary teachers should consider using tags for the various contexts in the classroom such as "Math", "Learning Centers" or "Buddy Reading" </li>
  <li>Teachers should also consider using tags to differentiate between notes on different topics such as "Behavior" or "Learning Goals"</li>
</ul>

app/views/static_pages/home.html.erb
<div class="row">
  <% if user_signed_in? %>
  <div class="col-md-8">
    <%= render "layouts/new_note_form" %>
  </div>
  <div class="col-md-4 homepage-sidebar">
    <h3>Select Class:</h2>
    <ul>
      <% @student_groups.each do |group| %>
        <li><%= link_to group.name, student_group_homepage_path(group.id)  %></li>
      <% end %>
      <li></li>
    </ul>
  </div>
  <% else %>
    <%= render "welcome_page" %>
  <% end %>
</div>