config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }, path_names: {sign_in: "login", sign_out: "logout"}
  resources 'users'
  resources 'student_group'
  resources 'students'
  resources 'student_notes'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get 'tags/:id/:tag', to: 'students#show', as: :tag
  get '/:student_group', to: 'static_pages#home', as: :student_group_homepage
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :student_group
  has_one :teacher, through: :student_group, class_name: "User"
  has_many :notes, dependent: :destroy, class_name: "StudentNote"
  acts_as_tagger
  validates :name, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!

  def show
    @student = Student.find(params[:id])
    @notes = @student.notes.all.order(created_at: "desc")
    @notes = @notes.tagged_with(params[:tag]) if params[:tag].present?
    @notes = @notes.after_date(Time.strptime(params[:date][:start_date], "%m/%d/%Y")) if params[:date] && params[:date][:start_date].length > 0
    @notes = @notes.before_date(Time.strptime(params[:date][:end_date], "%m/%d/%Y"))if params[:date] && params[:date][:end_date].length > 0
    @title = @student.name
    @context_list = create_context_list
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "report", layout: 'pdf.html.erb', page_size: "letter"
      end
    end
    authorize! :read, @student
  end

  def create
    group = StudentGroup.find(params[:student][:student_group_id])
    student = group.students.new
    student.name = params[:student][:name]
    if student.save
      flash[:success] = "Student Added"
      redirect_to group
    else
      flash[:danger] = "Oops! try again!"
      redirect_to group
    end
  end

  def edit
  end
  def update
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy
    redirect_to student.student_group
  end


  private

  def create_context_list
    list = [""]
    @student.notes.each { |note| note.context_list.each {|tag| list << tag }}
    list.uniq
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/show.html.erb
<div class="col-lg-10 notes-column">
  <ul class="student-notes">

    <% @notes.each do |note| %>
      <li>
        <div class="date"><strong><%= note.created_at.strftime("%a, %e %b") %></strong>

          <div class="links"><%= link_to "", edit_student_note_path(note), class: "glyphicon glyphicon-edit" %>  <%= link_to "", student_note_path(note), method: "delete", class: "glyphicon glyphicon-remove", data: {confirm: "Really delete?"}  %></div>
        </div>
        <div class="content"><%= note.content %></div>
        <% if note.context_list.length > 0 %>
        <div class="contexts"><strong>tags:</strong>
           <% note.context_list.each do |tag| %>
           <%= link_to tag, tag_path(note.student.id,tag) %>
           <% end %>

        </div>
        <% end %>
      </li>
    <% end %>

  </ul>
  <p><%= link_to "Delete Student", student_path, method: "delete", class: "btn btn-danger btn-sm", data: {confirm: "Really delete?"}%></p>
</div>
<div class="col-lg-2 context-list">
  <% if params[:tag] %>
  <% end %>
  <%= form_tag(student_path, method: "get", class: "filter-form") do %>
  <%= label_tag "Select Tag" %>
  <%= select_tag :tag, options_for_select(@context_list) %>
  <%= label_tag :date, "Select date range" %>
  <%= date_field :date, :start_date, placeholder: "start date", 'data-provide' => "datepicker", id: "datetimepicker1" %>
  <%= date_field :date, :end_date, placeholder: "end date", 'data-provide' => "datepicker" %>
  <%= submit_tag "Filter Notes", class: "btn btn-default"%>
  <p><%= link_to "Clear Filter", @student %></p>
  <% end %>

</div>

app/views/students/show.pdf.erb
<h1>Notes for <%= @student.name %></h1>
<h2>Class: <%= @student.student_group.name %>, Teacher: <%= @student.teacher.name %></h2>
<table class="notes">
  <col width="15%">
  <col width="65%">
  <col width="20%">
  <tr>
    <th>Date/Time</th>
    <th>Content</th>
    <th>Tags</th>
  </tr>
  <% @notes.each  do |note| %>
    <tr>
      <td>
        <%= note.created_at.strftime("%a, %e %b") %> <br>
        <%= note.created_at.strftime("%l:%M %p") %>
      </td>
      <td><%= note.content %></td>
      <td>
        <% note.context_list.each do |tag| %>
        <%= tag %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>