config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }, path_names: {sign_in: "login", sign_out: "logout"}
  resources 'users'
  resources 'student_group'
  resources 'students'
  resources 'student_notes'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get 'tags/:id/:tag', to: 'students#show', as: :tag
  get '/:student_group', to: 'static_pages#home', as: :student_group_homepage
end

app/models/student_group.rb
class StudentGroup < ApplicationRecord
  belongs_to :teacher, class_name: "User", foreign_key: "teacher_id"
  has_many :students, dependent: :destroy
  validates :name, presence: true
end

app/controllers/student_group_controller.rb
class StudentGroupController < ApplicationController
  before_action :authenticate_user!
  def show
    @student_group = StudentGroup.find(params[:id])
    @students = @student_group.students.all
    @title = @student_group.name
    @new_student = Student.new
    authorize! :read, @student_group
  end

  def new
    @student_group = StudentGroup.new
  end

  def create
    student_group = current_user.student_groups.new
    student_group.name = params[:student_group][:name]
    if student_group.save
      flash[:success] = "Class created!"
      redirect_to student_group
    else
    end
  end

  def edit
    @title = "Edit Class"
    @student_group = StudentGroup.find(params[:id])
    authorize! :read, @student_group
  end

  def update
    group = StudentGroup.find(params[:id])
    group.update_attributes(name: params[:student_group][:name])
    if group.save
      redirect_to group
    else
      flash[:error] = group.errors.full_messages.to_sentence
      redirect_to group
    end
  end

  def destroy
    group = StudentGroup.find(params[:id])
    group.destroy
    redirect_to group.teacher
  end

end

app/helpers/student_group_helper.rb
module StudentGroupHelper
end

app/views/student_group/edit.html.erb
<%= form_for @student_group do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>
<p>

</p>
<%= link_to "Delete Class", student_group_path, method: "delete", data: {confirm: "Really delete?"}, class: "btn btn-danger btn-sm" %>

app/views/student_group/show.html.erb
<h2>students:</h2>
<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.name, student %> | <%= student.notes.count %> notes</li>
  <% end %>
</ul>
<%= render "/layouts/new_student_form" %>
<p>
  
</p>
<%= link_to "Edit class", edit_student_group_path %>