config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' }, path_names: {sign_in: "login", sign_out: "logout"}
  resources 'users'
  resources 'student_group'
  resources 'students'
  resources 'student_notes'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get 'tags/:id/:tag', to: 'students#show', as: :tag
  get '/:student_group', to: 'static_pages#home', as: :student_group_homepage
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "alert alert-#{key} fade in alert-dismissible" %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="col-md-10 col-md-offset-1 footer">
  <p>©2016 <a href="http://codyloyd.com">Cody Loyd</a> <br>
    view project on <a href="https://github.com/codyloyd/anecdotal_notes">github</a>
  </p>
</div>

app/views/layouts/_header.html.erb
<div class="row">
  <div class="col-md-7 col-xs-9">
    <h1><%= @title %></h1>
  </div>
  <div class="col-md-5 col-xs-3 header-right">
    <div class="dropdown header-nav btn-group hidden-md hidden-lg">
      <button type="button" class="btn  btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      menu <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pull-right ">
        <% if current_user %>
          <li><%= link_to "New Note", root_url %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Help", help_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Log out", destroy_user_session_url, method: "delete"%></li>
          <% else %>
          <li><%= link_to "Log in", new_user_session_url %></li>
          <li><%= link_to "Sign up!", new_user_registration_url %></li>
          <% end %>
      </ul>
    </div>
    <ul class="header-nav hidden-sm hidden-xs btn-group pull-right">
      <% if current_user %>
          <li ><%= link_to "New note", root_url , class: "btn btn-default" %></li>
          <li ><%= link_to "Profile", current_user, class: "btn btn-default" %></li>
          <li ><%= link_to "Help", help_path , class: "btn btn-default"%></li>
          <li ><%= link_to "Log out", destroy_user_session_url, method: "delete", class: "btn btn-default"%></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_url , class: "btn btn-default"%></li> or
        <li><%= link_to "Sign up!", new_user_registration_url , class: "btn btn-default"%></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_new_class_form.html.erb
<%= form_for @new_student_group, url: student_group_index_path(@new_student_group), method: "post" do |f| %>
  <%= f.text_field :name, placeholder: "Class Name" %>
  <%= f.submit "Create New Class" %>
<% end %>

app/views/layouts/_new_note_form.html.erb
<%= form_for @note do |f| %>
<%= f.text_area :content, autofocus: true%><br>
<%= f.text_field :tag_list, placeholder: "add tags (separated by comma)"%>
<% if @selected_class %>
<%= f.select :student_id, @selected_class.students.collect{|p| [p.name, p.id]} %>
<% else %>
<%= f.select :student_id, current_user.students.collect{|p| [p.name, p.id]} %>
<% end %>
<%= f.submit "create note" %>
<% if @selected_class %>

<%= link_to "Go to class",  @selected_class, class: "goto-class-link"%>
<% end %>
<% end %>

app/views/layouts/_new_student_form.html.erb
<%= form_for @new_student do |f| %>
  <%= f.text_field :name, placeholder: "Student Name"%>
  <%= f.hidden_field(:student_group_id, :value => @student_group.id) %>
  <%= f.submit "Add Student" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anecdotal Notes</title>
    <link rel="icon" href="favicon.png">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, minimal-ui, mobile-web-app-capable">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/flash" %>
      <div class="col-lg-10 col-lg-offset-1 main-body">
        <%= render "layouts/header" %>
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
    <%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
     <link href="https://fonts.googleapis.com/css?family=Droid+Serif" rel="stylesheet">

  </head>
  <body>
    <div id="header">
      <!-- <%= wicked_pdf_image_tag 'mysite.jpg' %> -->
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>